export const IPC = {
  CATALOG_SEARCH: 'catalog:search',
  CATALOG_GET: 'catalog:get',
  CATALOG_TRENDING: 'catalog:trending',
  CATALOG_ENSURE: 'catalog:ensure',
  LIBRARY_LIST: 'library:list',
  LIBRARY_ADD: 'library:add',
  LIBRARY_UPDATE: 'library:update',
  LIBRARY_REMOVE: 'library:remove',
  LIBRARY_LOG_EPISODE: 'library:logEpisode',
  LIBRARY_EPISODES: 'library:episodes',
  LIBRARY_IMPORT_IMDB: 'library:importImdb',
  LIBRARY_LOG_VIEWING: 'library:logViewing',
  LIBRARY_VIEWINGS: 'library:viewings',
  STATS_GET: 'stats:get',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  TMDB_STATUS: 'tmdb:status',
  TMDB_SEARCH: 'tmdb:search',
  TMDB_TRENDING: 'tmdb:trending',
  TMDB_DETAILS: 'tmdb:details',
  TMDB_TRAILER: 'tmdb:trailer',
  TMDB_PROVIDERS: 'tmdb:providers',
  TMDB_SEASON: 'tmdb:season',
  TMDB_SHOW_STATUS: 'tmdb:showStatus',
  TMDB_DISCOVER: 'tmdb:discover',
  TMDB_GENRES: 'tmdb:genres',
  COLLECTION_LIST: 'collection:list',
  COLLECTION_CREATE: 'collection:create',
  COLLECTION_RENAME: 'collection:rename',
  COLLECTION_DELETE: 'collection:delete',
  COLLECTION_ITEMS: 'collection:items',
  COLLECTION_ADD: 'collection:add',
  COLLECTION_REMOVE: 'collection:remove',
  COLLECTION_MOVE: 'collection:move',
  NOTIFICATIONS_LIST: 'notifications:list',
  NOTIFICATIONS_DISMISS: 'notifications:dismiss',
  NOTIFICATIONS_CHECK: 'notifications:check',
  BACKUP_EXPORT: 'backup:export',
  BACKUP_IMPORT: 'backup:import',
  DIALOG_OPEN_FILE: 'dialog:openFile',
  APP_OPEN_DATA_DIR: 'app:openDataDir',
  APP_VERSION: 'app:version'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
